### ISSUE TITLE
Highlight whole line

### ISSUE THREAD

**Issue by daducci** [BlueSilverCat/highlight-registered-keyword#1]
Hi @BlueSilverCat ,

how is it possible to highlight the whole line containing a given keyword?
For example, imagine there I want to underline all the line corresponding to a `//` comment in `C++`?

Thanks,
Ale

**Comment by daducci** [comment]
I found a workaround: it suffices to add `width: 100% !important`. Sorry for posting an issue for this..

**Comment by BlueSilverCat** [comment]
Thanks for you comment.
I didn't know `width: 100% !important` is work.

Another solution.
for Patterns File.
e.g.
```
  {
    class: "keyword"
    pattern: "/(?:.*//.*\\r?\\n)/g"
  }
```
