### ISSUE TITLE
Error 'patternsFilePath' on install and any subsequent start with plugin enabled

### ISSUE THREAD

**Issue by TrySpace** [BlueSilverCat/highlight-registered-keyword#3]
This error occurs
```
Cannot read file from patternsFilePath
Error: ENOENT: no such file or directory, open ''
```

Even without any other plugins enabled. Atom 1.36.0 x64

**Comment by BlueSilverCat** [comment]
Thanks for your report.

Please set a patternsFilePath and a styles.less.
See sample file in readme.

Of course it's bad behavior.
I will fix it if I had more time.

**Comment by TrySpace** [comment]
I guess this happens because I had no `PatternsFilePath` set. But this is very uncommon behaviour for a plugin, it should work out of the box without configuring anything. 

Or preferably it should only give the error when I activate the plugin.

**Comment by BlueSilverCat** [comment]
oh, file is empty.
In any case, It's a very rudimentary bug.

Please wait for fix it.
but I don't know when that will be.
